options:
  lineNumbers: true
  spellcheck: true
editor:
  lineNumbers: true
  inputStyle: contenteditable
  spellcheck: true
# hexo-admin 默认文章参数
metadata:
  date:
  categories: new category
  tags: nothing
  comments: true
