# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Pillow-blog
subtitle: ""
description: ""
keywords:
author: Pillow
language: zh
timezone: ""

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: http://pillow-blog.top
permalink: :post/:abbrlink.html
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tag
archive_dir: archive
category_dir: category
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ""
filename_case: 0
render_drafts: false
post_asset_folder: true
marked:
  prependRoot: true
  postAsset: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ""
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ""

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ""
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: "mtime"

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: LiveForCode

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: git@github.com:Pilo-pillow/Pilo-pillow.github.io.git
  branch: main

# abbrlink config
abbrlink:
  alg: crc32
  rep: dec

# hexo-admin
admin:
  username: pillow
  password_hash: $2a$10$5ZrMTK/pm69NQg0X5SUjH.lU3fTrteDWK61iJU9.uDC0XWHpxBF9a
  secret: zhang20020304
  deployCommand: ./script/hexo-d.sh

# algolia配置
algolia:
  applicationID: "NOHU7IGAZZ"
  apiKey: "df648b72f1a5cc30d63ab0d18be51dc4"
  adminApiKey: "6d4537da603e99ac0b9949baf8329b5a"
  indexName: "Index"
  chunkSize: 5000
  hits:
    page: 10
  labels:
    placeholder: "搜索"
    empty: "未发现与 「${query}」 相关的内容"
    stats: "${hits} 条相关条目，使用了 ${time} 毫秒"
# Valine
# Valine:
#   switch: true
#   el: ".comments-content"
#   appId: "d1hS0ybtIaiwBcDQclZHeRW2-MdYXbMMI"
#   appKey: "qHnsGpnxIh9vAde3W5kW3HVG"
#   # 国内版本 LeanCloud 可以不用设置
#   serverURLs:
#   placeholder: "天空一声巨响"
#   avatar: "mm"
#   meta: "nick,mail,link"
#   requiredFields: "nick,mail"
#   pageSize: 5
#   lang: "zh-cn"
#   visitor: true

live2d:
  enable: true
  pluginModelPath: assets/
  model:
    # 模板目录，在node_modules里
    use: live2d-widget-model-shizuku
  display:
    position: right
    width: 280
    height: 560
  mobile:
    # 在手机端显示
    show: false
  rect: opacity:0.7
  #Latex
markdown_it_plus:
  highlight: true
  html: true
  xhtmlOut: true
  breaks: false
  langPrefix:
  linkify: true
  typographer: false
  quotes:
  plugins:
    - plugin:
        name: markdown-it-mark
        enable: false
